package com.VueTestWithSpring.enitites;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName = "user")
public class User {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey
    private String created_date;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(attributeName = "name",globalSecondaryIndexName = "gsi-name")
    private String name;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String password;
    @DynamoDBAttribute
    private String phoneNumber;
    @DynamoDBAttribute
    private String photo;
}
