package com.VueTestWithSpring.dto;

import com.VueTestWithSpring.enitites.User;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class UserDto {

    private String id;
    private String created_date;
    private String name;
    private String email;
    private String password;
    private String phoneNumber;
    private String photo;
    private String message;
    private int statusCode;
    private User user;
    private List<User> userList;
    private MultipartFile file;
}
